version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: solarwind1234
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  zenith-api:
    image: ghcr.io/ndemeshchenko/zenith-api:latest
    restart: always
    environment:
      MONGO_DATABASE: zenith
      MONGO_USERNAME: zenith
      MONGO_PASSWORD: zenith
      MONGO_HOST: localhost
      MONGO_PORT: 27017
    ports:
      - 8080:8080

#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: username
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongodb:27017/
